### ISSUE TITLE
 4.8.2. Implementar AJAX functions  

### ISSUE THREAD

**Issue by sanchez14424** [interfacesweb16-17/s4_t2#7]

**Comment by cgomez2016** [comment]
- [ ] Antonio

- [ ] Raquel

- [ ] Paula

- [ ] Raquel

- [ ] Cecilia

**Comment by Raquel-CM** [comment]
- [ ] Cecilia

- [ ] Antonio

- [ ] Paula

- [ ] Rafa

- [ ] Raquel
